#!/usr/bin/env node
// One-off generator for component/page skeletons per SPEC.md. Idempotent: skips files that already exist.
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const components = [
  { name: 'Header', spec: '## Nav' },
  { name: 'Footer', spec: '## Components — Footer' },
  { name: 'ThemeToggle', spec: '## Components — ThemeToggle' },
  { name: 'PixelMark', spec: '## Components — PixelMark' },
  { name: 'CTAButton', spec: '## Components — CTAButton' },
  { name: 'ContactCTA', spec: '## Pages & routes (/, /about)' },
  { name: 'Hero', spec: '## Components — Hero' },
  { name: 'ProofStrip', spec: '## Components — ProofStrip' },
  { name: 'CaseStudyCard', spec: '## Components — CaseStudyCard' },
  { name: 'PillarBlock', spec: '## Components — PillarBlock' },
  { name: 'EngagementStructure', spec: '## Components — EngagementStructure / EngagementPhase' },
  { name: 'EngagementPhase', spec: '## Components — EngagementStructure / EngagementPhase' },
  { name: 'AboutTeaser', spec: '## Components — AboutTeaser' },
  { name: 'ContactForm', spec: '## Components — ContactForm' },
];

const pages = [
  { path: 'about.astro', spec: '## Pages & routes — /about' },
  { path: 'contact.astro', spec: '## Pages & routes — /contact' },
  { path: 'work/index.astro', spec: '## Pages & routes — /work' },
];

const layouts = [{ name: 'BaseLayout', spec: '## Design tokens' }];

function componentStub({ name, spec }) {
  return `---
// Stub generated by scripts/scaffold-stubs.mjs — see SPEC.md ${spec}
interface Props {}
---

<div class="${name.toLowerCase()}">
  <!-- TODO: implement ${name} per SPEC.md ${spec} -->
</div>

<style>
</style>
`;
}

function pageStub({ spec }) {
  return `---
// Stub generated by scripts/scaffold-stubs.mjs — see SPEC.md ${spec}
---

<p>TODO: implement per SPEC.md ${spec}</p>
`;
}

function layoutStub({ spec }) {
  return `---
// Stub generated by scripts/scaffold-stubs.mjs — see SPEC.md ${spec}
interface Props {
  title: string;
}
const { title } = Astro.props;
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{title}</title>
  </head>
  <body>
    <slot />
  </body>
</html>
`;
}

function write(path, content) {
  if (existsSync(path)) {
    console.log(`skip (exists): ${path}`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote: ${path}`);
}

for (const c of components) {
  write(join(root, 'src/components', `${c.name}.astro`), componentStub(c));
}

for (const p of pages) {
  write(join(root, 'src/pages', p.path), pageStub(p));
}

for (const l of layouts) {
  write(join(root, 'src/layouts', `${l.name}.astro`), layoutStub(l));
}
